### ISSUE TITLE
Laravel 7

### ISSUE THREAD

**Issue by raisonon** [victoryoalli/laravel-code-generator#1]
Bit premature to create a ticket perhaps, but now I just tried with Laravel 7 (released today) and got the following error:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v7.0.1
    - Conclusion: don't install laravel/framework v7.0.1

...

    - don't install illuminate/filesystem v5.8.27|don't install laravel/framework v7.0.1

...

Installation failed, reverting ./composer.json to its original content.

**Comment by victoryoalli** [comment]
Solved with new version 1.0.7.
