### ISSUE TITLE
Where to add templates for custom template (Inertia.JS Vue Component)

### ISSUE THREAD

**Issue by raisonon** [victoryoalli/laravel-code-generator#2]
Hi there, fantastic code - thanks for this.

I'm trying to get this setup to work with Tailwind and Inertia.JS and instead of creating blade view files I want to crate .vue components in resources/js/Pages/FolderName/create.vue etc.

I can do this with the following custom command: https://gist.github.com/raisonon/83a9589a40fcc8e2d9200f42461eaec8

However, I'm still getting the View file templates. I've created my own create.vue etc. files in views/vendor/lavevel-code-generator/basic folder but no luck.

Any advice on how I can create and select my own template files for these vue files?

Thanks in advance

**Comment by victoryoalli** [comment]
Hi Elliot,

Yes you can create your own templates, in the resources/vendor directory
you will have something similar to this.


laravel-code-generator
├── Controllers
│   ├── API
│   │   └── modelController.blade.php
│   └── modelController.blade.php
├── js
│   ├── components
│   │   ├── model.blade.vue
│   │   ├── modelEditor.blade.vue
│   │   └── modelList.blade.vue
│   └── models
│       └── model.blade.js
└── views
    └── models
        └── index.blade.php

and then to create the vue file from the *model.blade.vue* template use a
similar line like the following in your command.


printif('Web Controller', CodeGenerator::generate($m,
*'/js/components/model'*, *"js/components/{$m->name}.vue"*, $force, $options
));


}
Let me know if you this helps.

VY

**Comment by raisonon** [comment]
Ah, maybe the issue is this command

`php artisan vendor:publish --provider="VictorYoalli\LaravelCodeGenerator\LaravelCodeGeneratorServiceProvider" --tag="views"`

Publishes to this folder location:

`/resources/views/vendor/laravel-code-generator/`

and it should be 

`resources/vendor/laravel-code-generator/`

Is this a problem unique to my setup?

**Comment by victoryoalli** [comment]
My mistake it publishes to

resources/views/vendor/laravel-code-generator/

that is correct!

**Comment by victoryoalli** [comment]
I will try to upload some javascript and vue examples during the weekend.

**Comment by victoryoalli** [comment]
were you able to solve it @raisonon ?

**Comment by raisonon** [comment]
Sorry I started to use PingCRM as a reference, but ended up being a bit more work than I anticipated so never completed:

https://github.com/inertiajs/pingcrm/tree/master/resources/js/Pages/Users

**Comment by raisonon** [comment]
Just circling back in case anyone picks this up in the future, but there are some stubs here that can be reused: https://github.com/Juhlinus/Inertia-Vue/tree/master/src/stubs
