### ISSUE TITLE
PhP 8 issue

### ISSUE THREAD

**Issue by Gerbenodk** [victoryoalli/laravel-code-generator#6]
- victoryoalli/laravel-code-generator is locked to version 1.0.9 and an update of this package was not requested.
    - victoryoalli/laravel-code-generator 1.0.9 requires php ^7.1 -> your php version (8.0.0) does not satisfy that requirement.
    - 
I fixed it by running:
composer require victoryoalli/laravel-code-generator --ignore-platform-reqs

**Comment by victoryoalli** [comment]
Now it's working with PHP8 out of the box. 

Thank you for reporting it.
