### ISSUE TITLE
php artisan code:generator 'Models\Datos' -FA proyecto de cero 

### ISSUE THREAD

**Issue by KoviScz** [victoryoalli/laravel-code-generator#7]
Unable to find 'App\Models\Datos' class
   TypeError 

  Argument 1 passed to App\Console\Commands\CodeGeneratorCommand::generate() must be an instance of VictorYoalli\LaravelCodeGenerator\Structure\Model, bool given, called in C:\wamp64\www\proyecto_taller\app\Console\Commands\CodeGeneratorCommand.php on line 80

 80|             $this->generate($m, $options, $theme, $force);
    81|         });
    82|     }
    83| 
  > 84|     public function generate(Model $m, $options, $theme, $force)
    85|     {
    86|         $option = (object) $options;
    87|         $folder = CodeHelper::plural(CodeHelper::snake($m->name));
    88|         if ($option->controller) {

  1   C:\wamp64\www\proyecto_taller\app\Console\Commands\CodeGeneratorCommand.php:80
      App\Console\Commands\CodeGeneratorCommand::generate("basic")

  2   C:\wamp64\www\proyecto_taller\vendor\laravel\framework\src\Illuminate\Support\Traits\EnumeratesValues.php:202
      App\Console\Commands\CodeGeneratorCommand::App\Console\Commands\{closure}("App\Models\Datos")
este problema aparece es un proyecto en blanco segui los paso para

**Comment by victoryoalli** [comment]
bugfix version 1.1.12 version solves this problem.
